// ref: https://docusaurus.io/docs/sidebar/multiple-sidebars#generating-pagination
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    'index',
    {
      type: 'doc',
      label: 'Philosophy',
      id: 'philosophy/index',
    },
    'gallery',
    {
      type: 'html',
      value: '<div class="sidebar-menu-divider"></div>',
      defaultStyle: true,
    },
    {
      type: 'doc',
      label: 'Voice',
      id: 'voice/index',
    },
    {
      type: 'category',
      label: 'Visual Language',
      collapsible: true,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'visual-language/index',
        },
        {
          type: 'doc',
          label: 'Logo',
          id: 'visual-language/logo',
        },
        {
          type: 'doc',
          label: 'Color',
          id: 'visual-language/color',
        },
        // {
        //   type: 'doc',
        //   label: 'Photography',
        //   id: 'visual-language/photography',
        // },
        // {
        //   type: 'doc',
        //   label: 'Illustration',
        //   id: 'visual-language/illustration',
        // },
        {
          type: 'category',
          label: 'Typography',
          collapsible: true,
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'visual-language/typography/index',
            },
            {
              type: 'doc',
              label: 'Web Environment',
              id: 'visual-language/typography/web-environment',
            },
            {
              type: 'doc',
              label: 'Non-web Environment',
              id: 'visual-language/typography/non-web-environment',
            },
          ],
        },
        {
          type: 'doc',
          label: 'Color',
          id: 'visual-language/color',
        },
        {
          type: 'category',
          label: 'Grid and Layout',
          collapsible: true,
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'visual-language/grid-and-layout/index',
            },
            {
              type: 'doc',
              label: 'Web Environment',
              id: 'visual-language/grid-and-layout/web-environment',
            },
            {
              type: 'doc',
              label: 'Non-web Environment',
              id: 'visual-language/grid-and-layout/non-web-environment',
            },
          ],
        },

        {
          type: 'doc',
          label: 'Photography',
          id: 'visual-language/photography',
        },
        {
          type: 'doc',
          label: 'Illustration',
          id: 'visual-language/illustration',
        },
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-menu-divider"></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'LSD - UI Library',
      collapsible: true,
      link: {
        type: 'generated-index',
        slug: 'category/lsd-ui-library',
      },
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'lsd/index',
        },
        {
          type: 'category',
          label: 'Design tokens',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'lsd/design-tokens',
            },
          ],
        },
        {
          type: 'category',
          label: 'Components',
          link: {
            type: 'doc',
            id: 'lsd/components/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'lsd/components',
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Templates',
      collapsible: true,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'doc',
          label: 'Presentation kits',
          id: 'templates/presentation-kits',
        },
        {
          type: 'doc',
          label: 'Social media assets',
          id: 'templates/social-media-assets',
        },
      ],
    },
  ],
}

module.exports = sidebars
