/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  main: [
    'index',
    {
      type: 'html',
      value: '<div class="sidebar-menu-section">Philosophy</div>', // The HTML to be rendered
      defaultStyle: true, // Use the default menu item styling
    },
    'philosophy/overview',
    'philosophy/principles',
    {
      type: 'html',
      value: '<div class="sidebar-menu-section">Brand Guidelines</div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Voice',
      collapsible: true,
      items: [
        {
          type: 'link',
          label: 'Overview',
          href: '/voice',
        },
      ],
    },
    {
      type: 'category',
      label: 'Visual Language',
      collapsible: true,
      items: [
        {
          type: 'link',
          label: 'Overview',
          href: '/visual-language',
        },
        {
          type: 'link',
          label: 'Logo',
          href: '/visual-language/logo',
        },
        {
          type: 'link',
          label: 'Typography',
          href: '/visual-language/typography',
        },
        {
          type: 'link',
          label: 'Color',
          href: '/visual-language/color',
        },
        {
          type: 'link',
          label: 'Grid & Layout',
          href: '/visual-language/grand-and-layout',
        },
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-menu-section">Resources & Tools</div>',
      defaultStyle: true,
    },
    'resources-and-tools/index',
    {
      type: 'category',
      label: 'LSD - UI library',
      collapsible: true,
      items: [
        {
          type: 'link',
          label: 'Overview',
          href: '/resources-and-tools/lsd',
        },
        {
          type: 'link',
          label: 'Design tokens',
          href: '/resources-and-tools/lsd/design-tokens',
        },
      ],
    },
    'resources-and-tools/presentation-kits',
    'resources-and-tools/logos-docusaurus-framework',
    {
      type: 'html',
      value: '<div class="sidebar-menu-section">Gallery</div>',
      defaultStyle: true,
    },
    'gallery/index',
  ],
}

module.exports = sidebars
