// ref: https://docusaurus.io/docs/sidebar/multiple-sidebars#generating-pagination
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  main: [
    'index',
    {
      type: 'category',
      label: 'Philosophy',
      collapsible: true,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'philosophy/overview',
        },
        {
          type: 'doc',
          label: 'Principles',
          id: 'philosophy/principles',
        },
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-menu-divider"></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Voice',
      collapsible: true,
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'voice/index',
        },
      ],
    },
    {
      type: 'category',
      label: 'Visual Language',
      collapsible: true,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'visual-language/index',
        },
        {
          type: 'doc',
          label: 'Logo',
          id: 'visual-language/logo',
        },
        {
          type: 'doc',
          label: 'Typography',
          id: 'visual-language/typography',
        },
        {
          type: 'doc',
          label: 'Color',
          id: 'visual-language/color',
        },
        {
          type: 'doc',
          label: 'Grid & Layout',
          id: 'visual-language/grid-and-layout',
        },
      ],
    },
    {
      type: 'html',
      value: '<div class="sidebar-menu-divider"></div>',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'LSD - UI Library',
      collapsible: true,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'doc',
          label: 'Overview',
          id: 'resources-and-tools/lsd/index',
        },
        {
          type: 'category',
          label: 'Design tokens',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'resources-and-tools/lsd/design-tokens',
            },
          ],
        },
        {
          type: 'category',
          label: 'Components',
          link: {
            type: 'doc',
            id: 'resources-and-tools/lsd/components/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'resources-and-tools/lsd/components',
            },
          ],
        },
      ],
    },
    'resources-and-tools/presentation-kits',
    'resources-and-tools/gallery',
  ],
}

module.exports = sidebars
